services:
  - type: web
    name: ftraise-status
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: STATUS_PORT
        value: 3001
      - key: MAIN_APP_URL
        value: https://ftraiseai.onrender.com
      - key: MONITOR_INTERVAL
        value: 60000
      - key: SOCKET_CORS_ORIGIN
        value: "*"
    healthCheckPath: /
    autoDeploy: true
